version: '3.7'
services:
    jupyter_lab:
        container_name: jupyter
        image: jupyter/datascience-notebook   
        environment:
            - JUPYTER_TOKEN=hi        
        ports:
            - "8080:8888"
        volumes:
            - Prueba:/Prueba
    my_image:
        container_name: my_container
        image: 881ab0b53993
        volumes:
            - Prueba:/Prueba
volumes:
    Prueba: