version: '3.7'
services:
    my_image:
        container_name: my_container
        build: ./Python
        volumes:
            - BartLevel:/app/Personajes/
    jupyter_lab:
        container_name: jupyter
        build: ./Jupyter      
        ports:
            - "8080:8888"
        volumes:
            - BartLevel:/home/jovyan/work/Personajes/
    
volumes:
    BartLevel: